name: Run Selenium tests
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Increase resources
        run: |
            echo "FS.increase resources if possible."
            echo 'chrome'
     
      - name: set up chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '131.0.6778.204'
          install-chromedriver: true
      - name: Print Chrome Version
        run: |
          google-chrome --version
      - name: Download ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
             chromedriver-version: '88.0.4324.96'
             chromeapp: chrome
      - run: |
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Print ChromeDriver Version
        run: |
              chromedriver --version
      - name: Build with Maven
        run: mvn test
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
